### ISSUE TITLE
Dashboards: Add clear both to .organization-item

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1121]
## Main asssignee: @
Add clear both every fifth of the organization item to prevent messy layout.
This should do the job.

```scss
.block {
    &.block-choose-organization {
        .organization-item {
            &:nth-of-type(4n + 1)
                clear:both;
            }    
        }
    }
}
```
## Context/goal: 
*explain why this issue was opened*
<img width="1143" alt="Screen Shot 2019-11-06 at 13 16 10" src="https://user-images.githubusercontent.com/38419514/68298359-70c24e80-0099-11ea-9470-948f8b73461b.png">
