### ISSUE TITLE
Image upload popup in right corner

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#464]
## Prerequisites

Click on upload image

## Description
![image](https://user-images.githubusercontent.com/10818702/49208673-b28e4380-f3b8-11e8-9997-75215d4b9b34.png)
Popup opens not in center of page but in right corner. This is a critical bug as the buttons are hidden.

use css to fix:
```css
.modal { 
display: flex;
align-items: center
}
.modal .modal-window {
min-height: 350px;
margin: 0 auto;
}
```

i think using absolute on the modal window with left and right margins is a bit messy. deleting it and using flex is more clean.
